//Docker
sudo docker pull postgres
sudo docker run --name=todo-db -e POSTGRES_PASSWORD=10007 -p 5436:5432 -d --rm postgres
sudo docker ps
sudo docker exec -it 7e19493c4d96b33dd8f0cf4f87606a1ac4dfab05a8986074f4f5133c058eb059 /bin/bash
psql -U postgres

// migrate
migrate create -ext sql -dir ./schema -seq init
migrate -path ./schema -database 'postgres://postgres:10007@localhost:5436/postgres?sslmode=disable' up
migrate -path ./schema -database 'postgres://postgres:10007@localhost:5436/postgres?sslmode=disable' down

// postgres
SELECT * FROM schema_migrations;
UPDATE schema_migrations SET version='000001', dirty=false;

// Go
go run cmd/main.go